# Generated by Django 2.1.5 on 2019-01-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterdeciser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='iteration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
