# Generated by Django 2.1.5 on 2019-01-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterdeciser', '0002_auto_20190115_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
